# Generated by Django 4.2.4 on 2023-08-31 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name=100)),
                ('description', models.CharField(verbose_name=250)),
            ],
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='measurements', serialize=False, to='measurement.sensor')),
                ('temperature', models.IntegerField()),
                ('created_at', models.DateField(auto_now=True)),
            ],
        ),
    ]
